language: rust
sudo: required
rust:
- 1.10
- stable
- beta
- nightly
matrix:
  include:
  - os: linux
    rust: stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo doc
