[package]

name = "uchardet"
version = "0.0.11"
authors = ["Eric Kidd <git@randomhacks.net>"]

description = "Detect character encodings using uchardet library"
license = "Unlicense"

documentation = "http://www.rust-ci.org/emk/rust-uchardet/doc/uchardet/"
repository = "https://github.com/emk/rust-uchardet"
readme = "README.md"
keywords = ["encoding", "text", "i18n"]

[dependencies]
libc = "0.1"

[dependencies.uchardet_sys]
path = "uchardet-sys"
version = "*"
